snippet apt-get
	RUN apt-get update -y && \
	  apt-get install -y ${1:} && \
	  rm -rf /var/lib/apt/lists/*
snippet wget
	wget --quiet ${1:} -O ${2:}
snippet curl
	curl --silent ${1:} -O ${2:}
snippet user
	RUN groupadd -g 999 ${1:appuser} && \
		useradd -r -u 999 -g $1 $1
	USER $1
